name: CICD

on:
  workflow_dispatch:

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        run: echo "Cloning the code"
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build using docket
        run: echo "Building using docker"
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Runnuning the test cases
        run: echo "Running the test"
  deploy:
    needs: [build,test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying on the machine
        run: echo "Deploying the code"
        
