# what is the goal of this workflow 
# Goal: Whenever someone changes the python code 
# the linter will check syntax and all
name: Auto Linter

on:
  push:
    paths: "*.py"


jobs:
  code:
    runs-on: ubuntu-latest
    # this step will automatically clone the code of the current branch into the runner
    steps:
      - name: Checkout/Clone the code
        uses: actions/checkout@v7
      - name: Install Linter
        run: pip install ruff
