# what is the goal of this workflow 
# Goal: Whenever someone changes the python code 
# the linter will check syntax and all
name: Auto Linter

on:
  push:
    paths: "*.py"


jobs:
  code:
    runs-on: ubuntu-latest
    # this step will automatically clone the code of the current branch into the runner
    steps:
      - name: Checkout/Clone the code
        uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Specify your preferred version here
      # This step will istall the linter
      - name: Install Linter
        run: pip install ruff
      # This step will check the Linter
      - name: Check the files for linting
        run: ruff check .
