#What is the goal of workflow
#Goal Whenever someone change the python code , the liner will check if the syntax is correct or not 

name: Auto linter

on:
  push:
    paths: "*.py"

jobs:
  code:
    runs-on: ubuntu-latest

    #this step will automatically clone the code for the current branch into the runner
    steps:
      - name: Checkout/Clone the code
        uses: actions/checkout@v7
        
        
